config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  # resources :profiles, only: [:show]

  resources :profile

  # get 'profile' => 'profile#show'

  get 'my_profile' => 'profile#my_profile'

  resources :bookings
  resources :friend_bookings


  resources :trips do
    resources :bookings
    resources :reviews, only: [:create]
    resources :pois, only: [:index, :show] do
  end
end
  # resources :features, only: [:index, :show]
  # resources :trip_features, only: []
  # Defines the root path route ("/")
  # root "articles#index"
end
#   resources :my_trips, only: [:index]
#   resources :trips
#   resources :pois, only: [:index, :show] do
#     resources :reviews, only: [:new, :create]
#     resources :my_trips, only: [:new, :create, :show]
#   end
#   resources :trip_pois, only: []
#   resources :reviews, only: [:destroy]
#   resources :users, only: [] do
#     resources :my_trips, only: [:index]
  # end

app/models/trip.rb
class Trip < ApplicationRecord
  validates :title, presence: true
  validates :start_point, presence: true
  validates :end_point, presence: true
  validates :summary, length: { in: 10..1000 }
  validates :region, presence: true
  validates :day, presence: true

  belongs_to :user
  has_many :reviews
  has_many :trip_pois
  has_many :pois, through: :trip_pois
  has_many :bookings
  has_many_attached :photos

  acts_as_favoritable
  accepts_nested_attributes_for :trip_pois
  scope :trending, -> {
    joins(:bookings)
      .group('trips.id')
      .order(Arel.sql('COUNT(*) DESC'))
  }
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = "title ILIKE :query OR start_point ILIKE :query OR end_point ILIKE :query OR region ILIKE :query"
      @trips = Trip.where(sql_query, query: "%#{params[:query]}%")
    else
      @trips = Trip.all
    end

    if params[:category].present?
      @pois = Poi.where(category: params[:category])
    else
      @pois = Poi.all
    end
    # The `geocoded` scope filters only flats with coordinates
    @markers = @pois.geocoded.map do |poi|
      {
        lat: poi.latitude,
        lng: poi.longitude,
        info_window: render_to_string(partial: "popup", locals: {poi: poi}),
        image_url: poi.image_url
      }
    end
  end

  def show
    @trip = Trip.find(params[:id])
    @review = Review.new
    @booking = Booking.new
    @pois = @trip.waypoint.present? ? Poi.where(id: @trip.waypoint.map(&:to_i)) : []
    # iterate over the array and for each trip_poi, find the poi it belongs to
    # return an array of pois

    @start_coords = Geocoder.search(@trip.start_point).first.coordinates.reverse
    @end_coords = Geocoder.search(@trip.end_point).first.coordinates.reverse

    @pois_names = Poi.where(id: @trip.waypoint.map(&:to_i)).map(&:name) if @pois.present?
    if @pois_names.present?
      @waypoint1 = Geocoder.search(@pois_names[0]).first&.coordinates&.reverse || false
      @waypoint2 = Geocoder.search(@pois_names[1]).first&.coordinates&.reverse || false
      @waypoint3 = Geocoder.search(@pois_names[2]).first&.coordinates&.reverse || false
      @waypoint4 = Geocoder.search(@pois_names[3]).first&.coordinates&.reverse || false
      @waypoint5 = Geocoder.search(@pois_names[4]).first&.coordinates&.reverse || false
    end
  end

  def new
    @trip = Trip.new
    @pois = Poi.all
  end

  def create
    @trip = Trip.new(trip_params)
    waypoint_ids = params["waypoint"].map { |id| id.to_i }
    @trip.waypoint = waypoint_ids
    @trip.user = current_user
    if @trip.save
      redirect_to trip_path(@trip), notice: "Trip created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      redirect_to @trip, notice: "Trip updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy!
    redirect_to trips_path, status: :see_other
  end

  private

  def trip_params
    params.require(:trip).permit(:title, :start_point, :end_point, :waypoint, :region, :summary, :day, photos: [])
  end
end

app/views/trips/_popup.html.erb
<div>
  <div class= "d-flex justify-content-center">
    <%= cl_image_tag poi.photo.key, height: 150, width: 200, class: "rounded", crop: :fill %>
  </div>
  <div>
    <h4><%= poi.name %></h4>
    <p><%= poi.address %></p>
  </div>
</div>

app/views/trips/edit.html.erb
<head>
  <script src='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.css' rel='stylesheet' />
  <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.js"></script>
  <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.css" type="text/css">
</head>
<div class="container my-3 py-3 px-3" data-controller="tom-select">
  <div class="card-background">
    <div class="d-flex col-5">
      <%= simple_form_for @trip do |f| %>
        <div>
          <h1 class="mb-2">Edit Trip</h1>
        </div>
        <%= f.input :title %>
        <%= f.input :start_point %>
        <%= f.input :waypoint, as: :select, collection: @pois %>
        <%= f.input :end_point %>
        <%= f.input :region %>
        <%= f.input :summary %>
        <%= f.input :day, collection: (1..50), label: 'Number of Days' %>
        <%= f.input :photos, label: 'Select up to 3 photos', as: :file, input_html: { multiple: true } %>
        <%= f.submit "Edit Trip", class: "btn btn-flat" %>
      <% end %>
      <div class="col-2">
        <div data-controller="map"
        id='map'
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        data-map-markers-value="<%= @markers.to_json %>"
        style='width: 100vh; height: 100vh;'>
        </div>
      </div>
    </div>
  </div>
  <hr class="solid">

app/views/trips/index.html.erb
<head>
  <script src='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.css' rel='stylesheet' />
  <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.js"></script>
  <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.css" type="text/css">
</head>
<div class="card-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.1)), url('<%= image_path "glencoe.jpg" %>')">
  Trips
</div>
<div>
  <br>
  <div class="poi-icons row text-center mb-2">
    <div class="d-flex justify-content-between poi-icons-links">
      <figure>
      <%= link_to trips_path do %>
        <i class="fa-solid fa-earth-europe fa-2x"></i>
        <figcaption>&nbspAll</figcaption>
      </figure>
      <% end %>
      <figure>
      <%= link_to trips_path(category: "Scenic Roads") do %>
          <i class="fa-solid fa-bridge-water fa-2x"></i>
          <figcaption>&nbspScenic Roads</figcaption>
        </figure>
      <% end %>
      <figure>
        <%= link_to trips_path(category: "Fun roads") do %>
        <i class="fa-solid fa-flag-checkered fa-2x"></i>
        <figcaption>&nbspFun Roads</figcaption>
      </figure>
      <% end %>
      <figure>
        <%= link_to trips_path(category: "Sights") do %>
        <i class="fa-solid fa-camera fa-2x"></i>
        <figcaption>&nbspSights</figcaption>
      </figure>
      <% end %>
      <figure>
        <%= link_to trips_path(category: "Landmarks") do %>
        <i class="fa-brands fa-fort-awesome fa-2x"></i>
        <figcaption>&nbspLandmarks</figcaption>
      </figure>
      <% end %>
      <figure>
        <%= link_to trips_path(category: "Sleeps") do %>
        <i class="fa-solid fa-bed fa-2x"></i>
        <figcaption>&nbspSleeps</figcaption>
      </figure>
      <% end %>
      <figure>
        <%= link_to trips_path(category: "Eats") do %>
        <i class="fa-solid fa-utensils fa-2x"></i>
        <figcaption>&nbsp&nbspEats</figcaption>
      </figure>
      <% end %>
      <figure>
        <%= link_to trips_path(category: "Services") do %>
        <i class="fa-solid fa-gas-pump fa-2x"></i>
        <figcaption>Services</figcaption>
      </figure>
      <% end %>
    </div>
  </div>
  <div class="main-container row">
    <div class="col-12 col-lg-5 mx-3">
      <div class="row">
        <% @trips.each do |trip| %>
          <div class="col-sm-6">
            <div class="card-trip flex mb-4">
              <div class="card-category">
                <%= link_to trip_path(trip) do %>
                  <% if trip.photos.attached? %>
                    <%= cl_image_tag trip.photos.first.key, height: 300, width: 400, crop: :fill, class:  %>
                  <% else %>
                    <%= image_tag "scotland-wallpaper.jpg", height: 300, width: 400, crop: :fill, class:  %>
                  <% end %>
                <% end %>
              </div>
              <div class="container card-category-infos pt-1">
                <div class="text-end">
                  <%= link_to profile_path(trip.user) do %>
                    <%= cl_image_tag trip.user.avatar.key, class: "card-trip-user avatar-bordered" %>
                  <% end %>
                </div>
                <h4><%= link_to trip.title, trip_path(trip), class: "card-category-h4 text-decoration-none" %> by <%= trip.user.username %></h4>
                <p><strong>From: </strong><%= trip.start_point %></p>
                <p><strong>To: </strong><%= trip.end_point %></p>
                <p><strong>Region: </strong> <%= trip.region %></p>
              </div>
              <div class="text-end mr-3">
                <div>
                  <h2><%= trip.day %> <%= trip.day > 1 ? "days" : "day" %></h2>
                </div>
                <div class="pb-3">
                  <% if trip.reviews.count > 0 %>
                    <h4>★ <strong><%= trip.reviews.average(:rating).round(2) %> </strong></h4>
                  <% else %>
                    <h4>No reviews</h4>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="card-background" data-controller="map"
      id='map'
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
      data-map-markers-value="<%= @markers.to_json %>"
      style='width: 100vh; height: 100vh;'></div>
  </div>
</div>
    <hr class="solid">

app/views/trips/new.html.erb
<head>
  <script src='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.css' rel='stylesheet' />
  <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.js"></script>
  <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.css" type="text/css">
</head>
<div class="container my-3 py-3 px-3" data-controller="tom-select">
  <div class="card-background">
    <div class="d-flex col-5">
      <%= simple_form_for [@trip] do |f| %>
        <div>
          <h1 class="mb-2">New Trip</h1>
        </div>
        <%= f.input :title %>
        <%= f.input :start_point %>
        <%= f.input :waypoint, as: :select, collection: @pois, label_method: :name, include_blank: true, input_html: { name: 'waypoint[]', class: 'stops' } %>
        <%= f.input :end_point %>
        <%= f.input :region %>
        <%= f.input :summary %>
        <%= f.input :day, collection: (1..50), label: 'Number of Days' %>
        <%= f.input :photos, label: 'Select up to 3 photos', as: :file, input_html: { multiple: true } %>
        <%= f.submit "Create Trip", class: "btn btn-success" %>
      <% end %>
      <div class="col-2">
        <div class="card-background" data-controller="map"
        id='map'
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        data-map-markers-value="<%= @markers.to_json %>"
        style='width: 100vh; height: 100vh;'>
        </div>
      </div>
    </div>
  </div>
</div>
<hr class="solid">

app/views/trips/show.html.erb
<head>
  <script src='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.css' rel='stylesheet' />
  <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.js"></script>
  <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.1/mapbox-gl-directions.css" type="text/css">
</head>
<div class="container">
  <br>
  <div class="row flex-wrap">
    <div class="row col-sm-4 card-background mb-3">
      <div class="card-background-infos py-3">
        <div>
          <h2><%= @trip.title %></h2>
          <h2>by <%= @trip.user.username %></h2>
          <%= link_to profile_path(@trip.user) do %>
            <%= cl_image_tag @trip.user.avatar.key, class: "card-trip-user avatar" %>
          <% end %>
          <p class= "text-end">Joined in <%= @trip.user.created_at.strftime("%B %Y")  %></p>
          <p><strong>From</strong></p>
          <p><%= @trip.start_point %></p>
          <p><strong>To</strong></p>
          <p><%= @trip.end_point %></p>
          <p><strong>Region</strong></p>
          <p><%= @trip.region %></p>
          <p><strong>Summary</strong></p>
          <p><%= @trip.summary %></p>
          <% if @trip.user == current_user %>
            <%= link_to "Edit Trip", edit_trip_path(@trip), class: "btn btn-flat my-2" %>
            <%= button_to "Delete Trip", trip_path(@trip), class: "btn btn-light", method: :delete, confirm: "Are you sure?"%>
          <% end %>
          <div class="text-end mr-3">
            <h2><%= @trip.day %> <%= @trip.day > 1 ? "days" : "day" %></h2>
            <% if @trip.reviews.count > 0 %>
              <h3 class="text-right">★ <strong><%= @trip.reviews.average(:rating).round(2) %> </strong>- <%= @trip.reviews.count %> reviews</h3>
            <% else %>
              <p>No reviews</p>
            <% end %>
          </div>
          <br>
          <br>
          <div>
            <% @trip.bookings.each do |booking| %>
              <%= link_to profile_path(booking.user) do %>
                <%= cl_image_tag booking.user.avatar.key, class: "mt-2 card-background-user avatar" %>
              <% end %>
            <% end %>
            <p>Saved this trip</p>
          </div>
        </div>
      </div>
    </div>
    <div class="flex col-sm-8 ml-2">
      <div class="card-background flex mb-3">
        <div id='map' style='width: 100%; height: 100vh;'>
        </div>
      </div>
    </div>
    <hr class="solid">
    <% if @trip.photos.attached? %>
      <div class="wrapper">
        <% unless @trip.photos.first.nil?%>
          <div class="item">
            <div class="polaroid">
              <%= cl_image_tag @trip.photos.first.key %>
            </div>
          </div>
        <% end %>
        <% unless @trip.photos.second.nil?%>
          <div class="item">
            <div class="polaroid">
              <%= cl_image_tag @trip.photos.second.key %>
            </div>
          </div>
        <% end %>
        <% unless @trip.photos.third.nil?%>
          <div class="item">
            <div class="polaroid">
              <%= cl_image_tag @trip.photos.third.key %>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="wrapper">
          <div class="item">
            <div class="polaroid"><%= image_tag "scotland-wallpaper.jpg" %>
            </div>
          </div>
        <% end %>
      </div>
      <hr class="solid">
      <div class="col-sm-6">
        <div class="card-background my-3 px-3 py-3">
          <h2>Reviews</h2>
          <div class="row">
            <div class="col-xs-4">
              <%= simple_form_for [@trip, @review] do |f| %>
                <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", input_html: {data: {controller: "star-rating"}} %>
                <%= f.input :content %>
                <%= f.submit "Add Review", class: "btn btn-flat mb-2"  %>
              <% end %>
            </div>
          </div>
          <div>
            <hr class="solid">
            <% if @trip.reviews.count > 0 %>
              <h2>User Reviews</h2>
              <ul class="list-group list-unstyled">
                <% @trip.reviews.each do |review| %>
                  <div>
                    <%= link_to profile_path(review.user) do %>
                      <%= cl_image_tag review.user.avatar.key, class: "mt-2 card-background-user avatar" %>
                    <%end%>
                    <li class="list-group-item-borderless"><strong><%= review.user.username %></strong>, <i><%= review.created_at.strftime("%b %d, %Y") %></i></li>
                    <li class="star-rating">
                      <% if review.rating %>
                        <%= '★' * review.rating %>
                      <%end%>
                    </li>
                    <li class="list-group-item-borderless mb-3"><%= review.content %></li>
                  </div>
                <% end %>
              </ul>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card-background my-3 px-3 py-3">
          <h2 class="mb-2">When would you like to go?</h2>
          <%= simple_form_for [@trip, @booking] do |f| %>
            <%= f.input :start_date, as: :string, input_html: { data: { controller: "flatpickr" } } %>
            <%= f.input :end_date, as: :string, input_html: { data: { controller: "flatpickr" } } %>
            <%= f.submit 'Save Trip', class: "btn btn-flat"%>
          <% end %>
        </div>
        <hr class="solid">
        <div>
          <div class="card-background my-3 px-3 py-3">
            <div>
              <h2 class="mb-2">Points of interest</h2>
              <% @trip.pois.each do |poi|%>
                <%= cl_image_tag poi.photo.key, height: 300, width: 400, class: "rounded", crop: :fill %>
                <h3 class="my-1"><strong><%= poi.category %></strong></h3>
                <h4 class="my-1"><strong><%= poi.name %></strong></h4>
                <p><strong>Description</strong></p>
                <p><%= poi.description %></p>
                <p><strong>Address</strong></p>
                <p><%= poi.address %></p>
                <br>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <hr class="solid">
  </div>
</div>
<script>
  mapboxgl.accessToken = "<%= ENV['MAPBOX_API_KEY'] %>"
  var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/cm11jun/clfipa1av000101rx4ues13y7',
    center: <%= @start_coords %>,
    zoom: 10
  });


  var directions = new MapboxDirections({
    accessToken: "<%= ENV['MAPBOX_API_KEY'] %>",
    unit: 'metric',
    profile: 'mapbox/driving'
  });
  map.addControl(directions, 'top-left');
  map.on('load', function() {
  directions.setOrigin(<%= @start_coords %>);
  directions.setDestination(<%= @end_coords %>);
  });
</script>
<% if @waypoint1 %>
  <script>
    directions.addWaypoint(0, <%= @waypoint1 %> );
  </script>
<% end %>
<% if @waypoint2 %>
  <script>
    directions.addWaypoint(1, <%= @waypoint2 %> );
  </script>
<% end %>
<% if @waypoint3 %>
  <script>
    directions.addWaypoint(2, <%= @waypoint3 %> );
  </script>
<% end %>
<% if @waypoint4 %>
  <script>
    directions.addWaypoint(3, <%= @waypoint4 %> );
  </script>
<% end %>
<% if @waypoint5 %>
  <script>
    directions.addWaypoint(4, <%= @waypoint5 %> );
  </script>
<% end %>