config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  # resources :profiles, only: [:show]

  resources :profile

  # get 'profile' => 'profile#show'

  get 'my_profile' => 'profile#my_profile'

  resources :bookings
  resources :friend_bookings


  resources :trips do
    resources :bookings
    resources :reviews, only: [:create]
    resources :pois, only: [:index, :show] do
  end
end
  # resources :features, only: [:index, :show]
  # resources :trip_features, only: []
  # Defines the root path route ("/")
  # root "articles#index"
end
#   resources :my_trips, only: [:index]
#   resources :trips
#   resources :pois, only: [:index, :show] do
#     resources :reviews, only: [:new, :create]
#     resources :my_trips, only: [:new, :create, :show]
#   end
#   resources :trip_pois, only: []
#   resources :reviews, only: [:destroy]
#   resources :users, only: [] do
#     resources :my_trips, only: [:index]
  # end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :trip
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
    @friend_bookings = FriendBooking.where(user_id: current_user)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @trip = Trip.find(params[:trip_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @trip = Trip.find(params[:trip_id])
    @booking.user = current_user
    @booking.trip = @trip
    if @booking.save
      redirect_to bookings_path, notice: "Trip saved!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def create
  #   @booking = Booking.new(booking_params)
  #   if @booking.save
  #     redirect_to @booking
  #   else
  #     render 'new'
  #   end
  # end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to bookings_path, notice: "Trip updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy!
    redirect_to bookings_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :trip_id, :start_date, :end_date)
  end
end

app/views/bookings/edit.html.erb
<div class="container w-50">
  <div class="card-background my-3 px-3 py-3">
    <h2>Edit dates for <%= @booking.trip.title %> by <%= @booking.trip.user.username %></h2>
    <br>
      <%= simple_form_for [@trip, @booking] do |f| %>
        <%= f.input :start_date, as: :string, input_html: { data: { controller: "flatpickr" } } %>
        <%= f.input :end_date, as: :string, input_html: { data: { controller: "flatpickr" } } %>
        <%= f.submit 'Edit Booking', class: "btn btn-flat"%>
      <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class='container card-background my-3'>
  <div class="main-container mx-2">
    <div class="col-sm-12">
      <h2 class="my-2">Saved Trips</h2>
      <div class="row">
        <% @bookings.each do |booking| %>
          <div class="col-sm-3">
            <div class="card-booking flex mb-4">
              <div class="card-category">
                <%= link_to trip_path(booking.trip) do %>
                  <% if booking.trip.photos.attached? %>
                    <%= cl_image_tag booking.trip.photos.first.key, height: 300, width: 400, crop: :fill, class:  %>
                  <% else %>
                    <%= image_tag "scotland-wallpaper.jpg", height: 300, width: 400, crop: :fill, class:  %>
                  <% end %>
                <% end %>
              </div>
              <div class="container card-category-infos pt-1">
                <div class="text-end">
                  <% if booking.trip.user %>
                    <%= link_to profile_path(booking.trip.user) do %>
                      <%= cl_image_tag booking.trip.user.avatar.key, class: "card-booking-user avatar-bordered" %>
                    <% end %>
                  <% end %>
                </div>
                <h4><%= link_to booking.trip.title, trip_path(booking.trip), class: "card-category-h4 text-decoration-none" %> by <%= booking.trip.user.username %></h4>
                <div class="card-category-infos">
                  <p class="mt-2"><strong>Booked on: </strong> <%= booking.created_at.strftime("%d/%m/%Y, %l:%M %p") %></p>
                  <p><strong>Start date: </strong> <%= booking.start_date.strftime("%d/%m/%Y") %></p>
                  <p><strong>End date: </strong> <%= booking.end_date.strftime("%d/%m/%Y") %></p>
                  <%= link_to "Edit Dates", edit_booking_path(booking), class: "btn btn-flat my-2" %>
                  <%= button_to "Cancel Trip", booking_path(booking), class: "btn btn-light", method: :delete, confirm: "Are you sure?"%>
                </div>
              </div>
              <div class="text-end mr-3">
                <div>
                  <h2><%= booking.trip.day %> <%= booking.trip.day > 1 ? "days" : "day" %></h2>
                </div>
                <div class="pb-3">
                  <% if booking.trip.reviews.count > 0 %>
                    <h4>★ <strong><%= booking.trip.reviews.average(:rating).round(2) %> </strong></h4>
                  <% else %>
                    <h4>No reviews</h4>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <hr class="solid">
  <div class="main-container mx-2">
    <div class="col-sm-12">
      <h2 class="my-2">Trips with Friends</h2>
      <div class="row">
        <% @friend_bookings.each do |friend_booking| %>
          <div class="col-sm-3">
            <div class="card-booking flex mb-4">
              <div class="card-category">
                <%= link_to trip_path(friend_booking.booking.trip) do %>
                  <% if friend_booking.booking.trip.photos.attached? %>
                    <%= cl_image_tag friend_booking.booking.trip.photos.first.key, height: 300, width: 400, crop: :fill, class:  %>
                  <% else %>
                    <%= image_tag "scotland-wallpaper.jpg", height: 300, width: 400, crop: :fill, class:  %>
                  <% end %>
                <% end %>
              </div>
              <div class="container card-category-infos pt-1">
                <div class="text-end">
                  <% if friend_booking.booking.trip.user %>
                    <%= link_to profile_path(friend_booking.booking.user.profile) do %>
                      <%= cl_image_tag friend_booking.booking.user.avatar.key, class: "card-booking-user avatar-bordered" %>
                    <% end %>
                    <%= link_to profile_path(current_user) do %>
                      <%= cl_image_tag current_user.avatar.key, class: "card-booking-user avatar-bordered" %>
                    <% end %>
                  <% end %>
                </div>
                <h4><%= link_to friend_booking.booking.trip.title, trip_path(friend_booking.booking.trip), class: "card-category-h4 text-decoration-none" %> by <%= friend_booking.booking.trip.user.username %></h4>
                <div class="card-category-infos">
                  <p class="mt-2"><strong>Saved on: </strong> <%= friend_booking.booking.created_at.strftime("%d/%m/%Y, %l:%M %p") %></p>
                  <p><strong>Start date: </strong> <%= friend_booking.booking.start_date.strftime("%d/%m/%Y") %></p>
                  <p><strong>End date: </strong> <%= friend_booking.booking.end_date.strftime("%d/%m/%Y") %></p>
                  <%= link_to "Edit Dates", edit_booking_path(friend_booking.booking), class: "btn btn-flat my-2" %>
                </div>
              </div>
              <div class="text-end mr-3">
                <div>
                  <h2><%= friend_booking.booking.trip.day %> <%= friend_booking.booking.trip.day > 1 ? "days" : "day" %></h2>
                </div>
                <div class="pb-3">
                  <% if friend_booking.booking.trip.reviews.count > 0 %>
                    <h4>★ <strong><%= friend_booking.booking.trip.reviews.average(:rating).round(2) %> </strong></h4>
                  <% else %>
                    <h4>No reviews</h4>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<hr class="solid">

app/views/bookings/new.html.erb
<%= simple_form_for [@trip, @booking] do |f| %>
  <%= f.input :start_date, as: :string, input_html: { data: { controller: "flatpickr" } } %>
  <%= f.input :end_date, as: :string, input_html: { data: { controller: "flatpickr" } } %>
  <%= f.submit 'Book Trip', class: "btn btn-flat"%>
<% end %>

app/views/bookings/show.html.erb
<p>User ID: <%= @booking.user_id %></p>
<p>Road Trip ID: <%= @booking.trip_id %></p>
<p>Start Date: <%= @booking.start_date %></p>
<p>End Date: <%= @booking.end_date %></p>

app/views/bookings/show.htnl.erb
<p>User ID: <%= @booking.user_id %></p>
<p>Road Trip ID: <%= @booking.trip_id %></p>
<p>Start Date: <%= @booking.start_date %></p>
<p>End Date: <%= @booking.end_date %></p>