config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  # resources :profiles, only: [:show]

  resources :profile

  # get 'profile' => 'profile#show'

  get 'my_profile' => 'profile#my_profile'

  resources :bookings
  resources :friend_bookings


  resources :trips do
    resources :bookings
    resources :reviews, only: [:create]
    resources :pois, only: [:index, :show] do
  end
end
  # resources :features, only: [:index, :show]
  # resources :trip_features, only: []
  # Defines the root path route ("/")
  # root "articles#index"
end
#   resources :my_trips, only: [:index]
#   resources :trips
#   resources :pois, only: [:index, :show] do
#     resources :reviews, only: [:new, :create]
#     resources :my_trips, only: [:new, :create, :show]
#   end
#   resources :trip_pois, only: []
#   resources :reviews, only: [:destroy]
#   resources :users, only: [] do
#     resources :my_trips, only: [:index]
  # end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h1>RoadTips</h1>
    <% end %>

<%= form_with url: trips_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Where to..."
  %>
  <%= submit_tag "Search Trips", class: "btn btn-flat" %>
<% end %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "All Trips", trips_path, class: "nav-link mx-3" %>
          </li>
          <%# <li class="nav-item"> %>
            <%# <%= link_to "Profile", profile_path(@profile), class: "nav-link mx-3" %>
          <%# </li> %>
          <li class="nav-item active">
            <%= link_to "Create new trip", new_trip_path, class: "btn btn-flat mx-3" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.avatar.present? %>
              <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <!-- add fallback image or text here -->
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", my_profile_path, class: "dropdown-item" %>
              <%= link_to "Community", profile_index_path, class: "dropdown-item" %>
              <%= link_to "Saved Trips", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>